// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyFYd2s82aTPWSuYIm2kNJmkX1d_5Iu30',
    appId: '1:122990125619:web:842e9d36d74c4d2da8f946',
    messagingSenderId: '122990125619',
    projectId: 'cloudkeja-d7e6b',
    authDomain: 'cloudkeja-d7e6b.firebaseapp.com',
    databaseURL: 'https://cloudkeja-d7e6b-default-rtdb.firebaseio.com',
    storageBucket: 'cloudkeja-d7e6b.appspot.com',
    measurementId: 'G-QSLL86NN6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHXxGvKllxGdqbryF_m2kxyIKVG7Uc4Ak',
    appId: '1:122990125619:android:e8a4e1379218571ea8f946',
    messagingSenderId: '122990125619',
    projectId: 'cloudkeja-d7e6b',
    databaseURL: 'https://cloudkeja-d7e6b-default-rtdb.firebaseio.com',
    storageBucket: 'cloudkeja-d7e6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC24h3r4_XbPYU9BCoPUwINIyb2zuInKpM',
    appId: '1:122990125619:ios:1a62f65a56f5bebfa8f946',
    messagingSenderId: '122990125619',
    projectId: 'cloudkeja-d7e6b',
    databaseURL: 'https://cloudkeja-d7e6b-default-rtdb.firebaseio.com',
    storageBucket: 'cloudkeja-d7e6b.appspot.com',
    iosClientId: '122990125619-sgogdtda9epn4tllirf4sjs1ajs0qg7c.apps.googleusercontent.com',
    iosBundleId: 'com.mumbo.cloudkeja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC24h3r4_XbPYU9BCoPUwINIyb2zuInKpM',
    appId: '1:122990125619:ios:1a62f65a56f5bebfa8f946',
    messagingSenderId: '122990125619',
    projectId: 'cloudkeja-d7e6b',
    databaseURL: 'https://cloudkeja-d7e6b-default-rtdb.firebaseio.com',
    storageBucket: 'cloudkeja-d7e6b.appspot.com',
    iosClientId: '122990125619-sgogdtda9epn4tllirf4sjs1ajs0qg7c.apps.googleusercontent.com',
    iosBundleId: 'com.mumbo.cloudkeja',
  );
}
